version: 2.1
orbs:
  packer: salaxander/packer@0.1
jobs:
  packer-example:
    executor: packer/default
    steps:
      - checkout
      - build:
          template: ami.json
          args: '-var aws_region=us-east-1'
workflows:
  version: 2
  packer:
    jobs:
      - packer-example
